### PR TITLE
Allows Jeeves to reply to it's own commands when dev mode is enabled.

### PR DESCRIPTION
**Pull request by Nessworthy**
Useful for testing on the same account as the bot.

### CODE REVIEW

**Comment by DaveRandom** [comment]
If this is necessary it feels like a regression, I'm sure @ekinhbayar did this once, although I can't find it anywhere :-/

This should be a separate option though IMO, e.g. `$config['dev-mode']['respond-to-self']` - `dev-mode` is designed as a map to enable stuff like this, it's just that it only has the one `enable` option at the moment. When I have my local in dev mode I still don't want it to respond to itself :-P

**Comment by Nessworthy** [comment]
Makes sense, I'll give it a shake!

**Comment by DaveRandom** [comment]
@Nessworthy it might be worth replacing the bool argument with some kind of "dev options" VO, i.e. something like:

```php
class DevOptions
{
    private $enable;
    private $respondToSelf;
    public function __construct(bool $enable, bool $respondToSelf)
    {
        $this->enable = $enable;
        $this->respondToSelf = $respondToSelf;
    }
    public function isEnabled()
    {
         return $this->enabled;
    }
    public function shouldRespondToSelf()
    {
        return $this->enable && $this->respondToSelf;
    }
}
```

... and where you are checking for it:

```php
if ($this->devOptions->respondToSelf() && ...)
```

**Comment by PeeHaa** [comment]
Yes. this has to be a regression.

@ekinhbayar implement the dev mode which should do what this PR aims to do.  
Before knowing what the best way to solve this is I would like to know how the regression happened.

**Comment by DaveRandom** [comment]
@PeeHaa the history is hard to read because I am a terrible person, but it looks like I probably screwed this up during the StackChat extraction/refactor, again because I am a terrible person.

The tl;dr is that I am terrible person.

**Comment by ekinhbayar** [comment]
I can't find it either :P thinking we used to have the websocket handler on Jeeves and this piece of code was there, so I'm guessing it was lost when StackChat emerged indeed. It doesn't really matter, this is the missing code so let's just merge it? :-)

**Comment by PeeHaa** [comment]
I like the idea of having a DevOptions like object available.

If we still want it create a dedicated issue. Merged this PR.

tnx @Nessworthy

**Pull request merged**
